### ISSUE TITLE
It won’t let me sideload or refresh any app

### ISSUE THREAD

**Issue by GlueHeart7** [DebianArch64/DebProvision#368]
it was working fine last week when I refreshed, but now it’s showing this
 “Failed
json: cannot unmarshal string into Go struct field
Tokens.tokens.adsid of type gsa.Token”

 error I don’t know what is the cause I re-downloaded everything logged out logged back in still the same error. I don’t know why this is happening.

<img width="642" height="1389" alt="Image" src="https://github.com/user-attachments/assets/44306ea5-aa49-4e4d-afd6-30efb08fe5b3" />

**Comment by DebianArch64** [comment]
> it was working fine last week when I refreshed, but now it’s showing this “Failed json: cannot unmarshal string into Go struct field Tokens.tokens.adsid of type gsa.Token”
> 
> error I don’t know what is the cause I re-downloaded everything logged out logged back in still the same error. I don’t know why this is happening.
> 
> <img alt="Image" width="642" height="1389" src="https://private-user-images.githubusercontent.com/110135745/494678418-44306ea5-aa49-4e4d-afd6-30efb08fe5b3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg5NDgxNTAsIm5iZiI6MTc1ODk0Nzg1MCwicGF0aCI6Ii8xMTAxMzU3NDUvNDk0Njc4NDE4LTQ0MzA2ZWE1LWFhNDktNGU0ZC1hZmQ2LTMwZWZiMDhmZTViMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyN1QwNDM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjBhNjhkOWUyOWNlYzM3MDk4NjliODYyM2M5NTJmNWZhOGE4YTAwMGQwZmJmZmUwMWExMWM2NzlmMWMwMDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OPr3sEcaVtpUwDvksMBgr_Jy3uj3Kf9JkNBgDeL9mpo">

Scarlet app and computer app must be on the latest versions, a change was made to the credential format that broke backwards compatibility

This file is called creds.json in case you want to forcefully remove it from the computer or phone, but logging out from the computer app and updating both should be enough

**Comment by FavaBeanOnly** [comment]
@DebianArch64 yeah i got around that part and i was able to refresh one app successfully but the other one is having problems now, idk what this is now

<img width="727" height="419" alt="Image" src="https://github.com/user-attachments/assets/9d447c83-657f-491a-9d60-269d43ae690c" />

**Comment by DebianArch64** [comment]
> [@DebianArch64](https://github.com/DebianArch64) yeah i got around that part and i was able to refresh one app successfully but the other one is having problems now, idk what this is now
> 
> <img alt="Image" width="727" height="419" src="https://private-user-images.githubusercontent.com/110135745/494684333-9d447c83-657f-491a-9d60-269d43ae690c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg5NTA3ODIsIm5iZiI6MTc1ODk1MDQ4MiwicGF0aCI6Ii8xMTAxMzU3NDUvNDk0Njg0MzMzLTlkNDQ3YzgzLTY1N2YtNDkxYS05ZDYwLTI2OWQ0M2FlNjkwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyN1QwNTIxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjcxZTkzZTM5MDY5NTc0MTZlZGY2NGYxN2M0ZTI2YzFiNDk1MDQxMzJjNWZlYWIyMmE5ZjAzZGE1NjI1MWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kGUdvggVvQUKtMnP32TF7tty1vZmCmOyoSzjh5KEtfQ">

Just for clarification to refresh apps you do it from the Scarlet app that installs, you click the icon of the app you want to refresh from the "Installed Apps" section and it gives options and expiration date information.

How refresh works for computer methods is swapping the mobileprovision not resideloading, so that should fix any sort of issues. That's also the recommended way because you can do that without a computer if you setup wireguard including installs

**Comment by GlueHeart7** [comment]
> > [@DebianArch64](https://github.com/DebianArch64) yeah i got around that part and i was able to refresh one app successfully but the other one is having problems now, idk what this is now
> > <img alt="Image" width="727" height="419" src="https://private-user-images.githubusercontent.com/110135745/494684333-9d447c83-657f-491a-9d60-269d43ae690c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg5NTA3ODIsIm5iZiI6MTc1ODk1MDQ4MiwicGF0aCI6Ii8xMTAxMzU3NDUvNDk0Njg0MzMzLTlkNDQ3YzgzLTY1N2YtNDkxYS05ZDYwLTI2OWQ0M2FlNjkwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyN1QwNTIxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjcxZTkzZTM5MDY5NTc0MTZlZGY2NGYxN2M0ZTI2YzFiNDk1MDQxMzJjNWZlYWIyMmE5ZjAzZGE1NjI1MWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kGUdvggVvQUKtMnP32TF7tty1vZmCmOyoSzjh5KEtfQ">
> 
> Just for clarification to refresh apps you do it from the Scarlet app that installs, you click the icon of the app you want to refresh from the "Installed Apps" section and it gives options and expiration date information.
> 
> How refresh works for computer methods is swapping the mobileprovision not resideloading, so that should fix any sort of issues. That's also the recommended way because you can do that without a computer if you setup wireguard including installs

yeah i know that, i tried both ways it still shows the same error even if i install it as a new app rather than refreshing it, it shows the same error every time hhhh

error is “Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.picsart....” something something

I think it only happens with this app? it was working fine before. Also, I’ve tried different versions of this same app and none of them works hh

![Image](https://github.com/user-attachments/assets/2724c33b-2704-4106-94d0-9f608b8c7e96)

**Comment by DebianArch64** [comment]
Yeah I took a look at the IPA and found something I've never seen before, it's likely the cause. There is an "Extensions" folder with an appex (app extension), it's likely that my current code doesn't see that app extension because it's not inside "PlugIns" and therefore doesn't patch it to match parent bundleId. I'll go ahead and make some changes right now

**Comment by GlueHeart7** [comment]
> Yeah I took a look at the IPA and found something I've never seen before, it's likely the cause. There is an "Extensions" folder with an appex (app extension), it's likely that my current code doesn't see that app extension because it's not inside "PlugIns" and therefore doesn't patch it to match parent bundleId. I'll go ahead and make some changes right now

It worked for now, but only if I install the app through the computer scarlet app, it still shows the same error if I do it from the phone scarlet app, idk why

**Comment by DebianArch64** [comment]
> > Yeah I took a look at the IPA and found something I've never seen before, it's likely the cause. There is an "Extensions" folder with an appex (app extension), it's likely that my current code doesn't see that app extension because it's not inside "PlugIns" and therefore doesn't patch it to match parent bundleId. I'll go ahead and make some changes right now
> 
> It worked for now, but only if I install the app through the computer scarlet app, it still shows the same error if I do it from the phone scarlet app, idk why

I pushed an update to the Scarlet app that might resolve the issue for you, let me know if you ever run into it again. For now I'm heading to sleep, Texas timezone ✌️

^^ update via hitting "Install Scarlet" from computer app

**Comment by GlueHeart7** [comment]
> > > Yeah I took a look at the IPA and found something I've never seen before, it's likely the cause. There is an "Extensions" folder with an appex (app extension), it's likely that my current code doesn't see that app extension because it's not inside "PlugIns" and therefore doesn't patch it to match parent bundleId. I'll go ahead and make some changes right now
> > 
> > 
> > It worked for now, but only if I install the app through the computer scarlet app, it still shows the same error if I do it from the phone scarlet app, idk why
> 
> I pushed an update to the Scarlet app that might resolve the issue for you, let me know if you ever run into it again. For now I'm heading to sleep, Texas timezone ✌️
> 
> ^^ update via hitting "Install Scarlet" from computer app

 ehh ion think it worked i still get the same error when installing from the phone scarlet app, it works with the computer scarlet app anyways I also get this issue now whenever I close the computer scarlet app and reopen it i have to login with the apple id every time,  it used to be a one-time thing before, now i have to enter the password everytime hhh
and rest well.

**Comment by DebianArch64** [comment]
> > > > Yeah I took a look at the IPA and found something I've never seen before, it's likely the cause. There is an "Extensions" folder with an appex (app extension), it's likely that my current code doesn't see that app extension because it's not inside "PlugIns" and therefore doesn't patch it to match parent bundleId. I'll go ahead and make some changes right now
> > > 
> > > 
> > > It worked for now, but only if I install the app through the computer scarlet app, it still shows the same error if I do it from the phone scarlet app, idk why
> > 
> > 
> > I pushed an update to the Scarlet app that might resolve the issue for you, let me know if you ever run into it again. For now I'm heading to sleep, Texas timezone ✌️
> > ^^ update via hitting "Install Scarlet" from computer app
> 
> ehh ion think it worked i still get the same error when installing from the phone scarlet app, it works with the computer scarlet app anyways I also get this issue now whenever I close the computer scarlet app and reopen it i have to login with the apple id every time, it used to be a one-time thing before, now i have to enter the password everytime hhh and rest well.

Yeah I know about that, the last change to login introduced expiration dates to determine when a token expires. The dates given back by Apple are oddly the same day. I'll be able to look into it more when I'm done with some college assignments for this week
